---
repos:
  - repo: git@github.com:CloudMonocle/pre-commit-checks.git
    rev: 463bbedd8ae2bcbf8dbeb545867437ccb06e4d93
    hooks:
      #Code checks
      - id: check-added-large-files
        args: ["--maxkb=1000"]
        exclude: "notebooks"
      - id: check-json
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: trailing-whitespace
      #IaC checks
      - id: terraform-fmt
      - id: terraform_tflint
      - id: terraform-validate
      #python checks
      - id: pylint
      - id: black
      - id: flake8
      - id: mypy
      - id: isort
      - id: bandit
      #Spell checkers
#      - id: codespell
