[project]
name = "lotochecker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "boto3==1.40.4",
    "pandas>=2.3.3",
]
