---
name: Terraform Checks/Deploy(Dev)
permissions:
  id-token: write
  contents: read
  pull-requests: write
  statuses: write
  checks: write
  security-events: write
  issues: write

on:
  pull_request:
    branches:
      - main
    paths:
      - terraform/**
      - lambda/**

env:
  AWS_REGION: "eu-west-1"

defaults:
  run:
    shell: bash
    working-directory: terraform

jobs:
  pytest_lambda:
    runs-on: ubuntu-latest
    environment:
      name: development-plan
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v5.4.0
        with:
          python-version: 3.x # Use any supported Python version

      - name: AWS login main account
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.MAIN_AWS_ACCOUNT_ID }}:role/${{ vars.MAIN_AWS_ROLE }}
          role-session-name: ${{ github.sha }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install dependencies
        shell: sh
        run: |
          pip install boto3 requests pytest pytest-md pytest-emoji

      - name: Run pytest
        uses: pavelzw/pytest-action@v2
        with:
          verbose: true
          emoji: true
          job-summary: true
          custom-arguments: "-v"
          click-to-expand: true
          report-title: "Test Report"

  terraform_plan:
    concurrency:
      group: terraform-plan
      cancel-in-progress: false
    runs-on: ubuntu-latest
    environment:
      name: development-plan
    steps:
      - name: install terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Set up Python
        uses: actions/setup-python@v5.4.0
        with:
          python-version: 3.x # Use any supported Python version

      - name: AWS login main account
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.MAIN_AWS_ACCOUNT_ID }}:role/${{ vars.MAIN_AWS_ROLE }}
          role-session-name: ${{ github.sha }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Terraform init
        env:
          TF_VAR_AWS_ACCOUNT_ID: ${{ vars.DEPLOY_AWS_ACCOUNT_ID }}
          TF_VAR_AWS_ROLE_NAME: ${{ vars.DEPLOY_AWS_ROLE }}
          TF_VAR_github_token: ${{ secrets.GITHUB_TOKEN }}

        shell: sh
        run: |
          terraform init -input=false -no-color -upgrade -reconfigure -backend-config=config/development/backend.conf -var-file=config/development/terraform.tfvars
        working-directory: terraform

      - name: Terraform Validate
        if: github.event_name == 'pull_request'
        shell: sh
        run: |
          terraform validate -no-color
        continue-on-error: true
        working-directory: terraform

      - name: Terraform Plan/Show
        if: github.event_name == 'pull_request'
        id: terraform_plan
        shell: sh
        run: |
          terraform plan -refresh=true -out=plan.out -var-file=config/development/terraform.tfvars
          terraform show -json plan.out | jq . > plan.json
        env:
          TF_VAR_aws_account_id: ${{ vars.DEPLOY_AWS_ACCOUNT_ID }}
          TF_VAR_aws_role_name: ${{ vars.DEPLOY_AWS_ROLE }}
          TF_VAR_github_token: ${{ secrets.GITHUB_TOKEN }}
        working-directory: terraform

      - name: Checkov
        id: checkov
        uses: ghostfacts/checkov@main
        with:
          planfilename: plan.json
          path: terraform
          githubapi: ${{ secrets.GITHUB_TOKEN }}

  terraform_deploy:
    concurrency:
      group: terraform-deploy
      cancel-in-progress: false
    runs-on: ubuntu-latest
    needs: terraform_plan
    environment:
      name: development-deploy
    steps:
      - name: AWS login main account
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.MAIN_AWS_ACCOUNT_ID }}:role/${{ vars.MAIN_AWS_ROLE }}
          role-session-name: ${{ github.sha }}
          aws-region: ${{ env.AWS_REGION }}

      - name: install terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Set up Python
        uses: actions/setup-python@v5.4.0
        with:
          python-version: "3.10" # Use any supported Python version

      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Terraform init
        shell: sh
        env:
          TF_VAR_aws_account_id: ${{ vars.DEPLOY_AWS_ACCOUNT_ID }}
          TF_VAR_aws_role_name: ${{ vars.DEPLOY_AWS_ROLE }}
          TF_VAR_github_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          terraform init -input=false -no-color -upgrade -reconfigure -backend-config=config/development/backend.conf -var-file=config/development/terraform.tfvars
        working-directory: terraform

      - name: Terraform apply
        shell: sh
        env:
          TF_VAR_aws_account_id: ${{ vars.DEPLOY_AWS_ACCOUNT_ID }}
          TF_VAR_aws_role_name: ${{ vars.DEPLOY_AWS_ROLE }}
          TF_VAR_github_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          terraform apply -var-file=config/development/terraform.tfvars --auto-approve
        working-directory: terraform

  # trigger_lambda_test:
  #   concurrency:
  #     group: terraform-deploy
  #     cancel-in-progress: false
  #   runs-on: ubuntu-latest
  #   needs: terraform_deploy
  #   environment:
  #     name: development-deploy
  #   steps:
  #     - name: AWS login main account
  #       uses: aws-actions/configure-aws-credentials@v4
  #       with:
  #         role-to-assume: arn:aws:iam::${{ vars.MAIN_AWS_ACCOUNT_ID }}:role/${{ vars.MAIN_AWS_ROLE }}
  #         role-session-name: ${{ github.sha }}-main
  #         aws-region: ${{ env.AWS_REGION }}

  #     - name: Switch to Deploy Account
  #       uses: aws-actions/configure-aws-credentials@v4
  #       with:
  #         role-to-assume: arn:aws:iam::${{ vars.DEPLOY_AWS_ACCOUNT_ID }}:role/${{ vars.DEPLOY_AWS_ROLE }}
  #         role-session-name: ${{ github.sha }}-test
  #         aws-region: ${{ env.AWS_REGION }}

  #     - name: Trigger Lambda Test Event
  #       shell: sh
  #       run: |
  #         aws lambda invoke --function-name loto-checker-dev-lotoCheckerFunction response.json
  #         cat response.json
