---
name: Terraform Deploy(prod)
permissions:
  id-token: write
  contents: read
  pull-requests: write
  statuses: write
  checks: write
  security-events: write
  issues: write

on:
  push:
    branches:
      - main
    paths:
      - terraform/**

defaults:
  run:
    shell: bash
    working-directory: terraform

jobs:
  terraform_plan:
    concurrency:
      group: terraform-plan
      cancel-in-progress: false
    runs-on: ubuntu-latest
    environment:
      name: production-plan
    steps:
      - name: install terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Set up Python
        uses: actions/setup-python@v5.4.0
        with:
          python-version: 3.x # Use any supported Python version

      - name: AWS login main account
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.MAIN_AWS_ACCOUNT_ID }}:role/${{ vars.MAIN_AWS_ROLE }}
          role-session-name: ${{ github.sha }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Terraform init
        env:
          TF_VAR_AWS_ACCOUNT_ID: ${{ vars.DEPLOY_AWS_ACCOUNT_ID }}
          TF_VAR_AWS_ROLE_NAME: ${{ vars.DEPLOY_AWS_ROLE }}
          TF_VAR_github_token: ${{ secrets.GITHUB_TOKEN }}

        shell: sh
        run: |
          terraform init -input=false -no-color -upgrade -reconfigure -backend-config=config/production/backend.conf -var-file=config/production/terraform.tfvars
        working-directory: terraform

      - name: Terraform Validate
        if: github.event_name == 'pull_request'
        shell: sh
        run: |
          terraform validate -no-color
        continue-on-error: true
        working-directory: terraform

      - name: Terraform Plan/Show
        if: github.event_name == 'pull_request'
        id: terraform_plan
        shell: sh
        run: |
          terraform plan -refresh=true -out=plan.out -var-file=config/production/terraform.tfvars
          terraform show -json plan.out | jq . > plan.json
        env:
          TF_VAR_aws_account_id: ${{ vars.DEPLOY_AWS_ACCOUNT_ID }}
          TF_VAR_aws_role_name: ${{ vars.DEPLOY_AWS_ROLE }}
          TF_VAR_github_token: ${{ secrets.GITHUB_TOKEN }}
        working-directory: terraform

  terraform_deploy:
    concurrency:
      group: terraform-deploy
      cancel-in-progress: false
    runs-on: ubuntu-latest
    needs: terraform_plan
    environment:
      name: production-deploy
    steps:
      - name: AWS login main account
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.MAIN_AWS_ACCOUNT_ID }}:role/${{ vars.MAIN_AWS_ROLE }}
          role-session-name: ${{ github.sha }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: install terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Set up Python
        uses: actions/setup-python@v5.4.0
        with:
          python-version: "3.10" # Use any supported Python version

      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Terraform init
        shell: sh
        env:
          TF_VAR_aws_account_id: ${{ vars.DEPLOY_AWS_ACCOUNT_ID }}
          TF_VAR_aws_role_name: ${{ vars.DEPLOY_AWS_ROLE }}
          TF_VAR_github_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          terraform init -input=false -no-color -upgrade -reconfigure -backend-config=config/production/backend.conf -var-file=config/production/terraform.tfvars
        working-directory: terraform

      - name: Terraform apply
        shell: sh
        env:
          TF_VAR_aws_account_id: ${{ vars.DEPLOY_AWS_ACCOUNT_ID }}
          TF_VAR_aws_role_name: ${{ vars.DEPLOY_AWS_ROLE }}
          TF_VAR_github_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          terraform apply -var-file=config/production/terraform.tfvars --auto-approve
        working-directory: terraform
