---
name: Terraform Deploy(prod)
permissions:
  id-token: write
  contents: read
  pull-requests: write
  statuses: write
  checks: write
  security-events: write
  issues: write

on:
  push:
    branches:
      - main
    paths:
      - terraform/**
      - lambda/**
      - .github/workflows/deploy_prod.yaml

env:
  AWS_REGION: "eu-west-1"

defaults:
  run:
    shell: bash
    working-directory: terraform

jobs:
  destroy_dev_environment:
    concurrency:
      group: terraform-deploy
      cancel-in-progress: false
    runs-on: ubuntu-latest
    environment:
      name: development-deploy
    steps:
      - name: AWS login main account
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.MAIN_AWS_ACCOUNT_ID }}:role/${{ vars.MAIN_AWS_ROLE }}
          role-session-name: ${{ github.sha }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: install terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Set up Python
        uses: actions/setup-python@v5.4.0
        with:
          python-version: "3.13" # Use any supported Python version

      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Terraform init
        shell: sh
        env:
          TF_VAR_aws_account_id: ${{ vars.DEPLOY_AWS_ACCOUNT_ID }}
          TF_VAR_aws_role_name: ${{ vars.DEPLOY_AWS_ROLE }}
          TF_VAR_github_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          terraform init -input=false -no-color -upgrade -reconfigure -backend-config=config/development/backend.conf -var-file=config/development/terraform.tfvars
        working-directory: terraform

      - name: Terraform destroy
        shell: sh
        env:
          TF_VAR_aws_account_id: ${{ vars.DEPLOY_AWS_ACCOUNT_ID }}
          TF_VAR_aws_role_name: ${{ vars.DEPLOY_AWS_ROLE }}
          TF_VAR_github_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          terraform destroy -var-file=config/development/terraform.tfvars --auto-approve
        working-directory: terraform

  deploy_prod_environment:
    concurrency:
      group: terraform-deploy
      cancel-in-progress: false
    runs-on: ubuntu-latest
    needs: destroy_dev_environment
    environment:
      name: production-deploy
    steps:
      - name: AWS login main account
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.MAIN_AWS_ACCOUNT_ID }}:role/${{ vars.MAIN_AWS_ROLE }}
          role-session-name: ${{ github.sha }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: install terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Set up Python
        uses: actions/setup-python@v5.4.0
        with:
          python-version: "3.10" # Use any supported Python version

      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Terraform init
        shell: sh
        env:
          TF_VAR_aws_account_id: ${{ vars.DEPLOY_AWS_ACCOUNT_ID }}
          TF_VAR_aws_role_name: ${{ vars.DEPLOY_AWS_ROLE }}
          TF_VAR_github_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          terraform init -input=false -no-color -upgrade -reconfigure -backend-config=config/production/backend.conf -var-file=config/production/terraform.tfvars
        working-directory: terraform

      - name: Terraform apply
        shell: sh
        env:
          TF_VAR_aws_account_id: ${{ vars.DEPLOY_AWS_ACCOUNT_ID }}
          TF_VAR_aws_role_name: ${{ vars.DEPLOY_AWS_ROLE }}
          TF_VAR_github_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          terraform apply -var-file=config/production/terraform.tfvars --auto-approve
        working-directory: terraform
